# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infobox',
            fields=[
                ('ani_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ani_type', models.CharField(blank=True, max_length=100)),
                ('name_jp', models.CharField(blank=True, max_length=100)),
                ('name_cn', models.CharField(blank=True, max_length=100)),
                ('total_episode', models.CharField(blank=True, max_length=100)),
                ('broadcast_time', models.CharField(blank=True, max_length=100)),
                ('broadcast_over', models.CharField(blank=True, max_length=100)),
                ('broadcast_state', models.CharField(blank=True, max_length=100)),
                ('original', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('script', models.CharField(blank=True, max_length=500)),
                ('storyboard', models.CharField(blank=True, max_length=500)),
                ('perform', models.CharField(blank=True, max_length=500)),
                ('music', models.CharField(blank=True, max_length=100)),
                ('character_original_bill', models.CharField(blank=True, max_length=100)),
                ('character_design', models.CharField(blank=True, max_length=100)),
                ('machine_design', models.CharField(blank=True, max_length=100)),
                ('art_director', models.CharField(blank=True, max_length=100)),
                ('color_design', models.CharField(blank=True, max_length=100)),
                ('animation_director', models.CharField(blank=True, max_length=500)),
                ('photo_director', models.CharField(blank=True, max_length=100)),
                ('original_painting', models.CharField(blank=True, max_length=1000)),
                ('sec_original_painting', models.CharField(blank=True, max_length=100)),
                ('animate_check', models.CharField(blank=True, max_length=100)),
                ('background_art', models.CharField(blank=True, max_length=100)),
                ('color_designation', models.CharField(blank=True, max_length=100)),
                ('theme_arranger', models.CharField(blank=True, max_length=100)),
                ('theme_word', models.CharField(blank=True, max_length=100)),
                ('theme_compose', models.CharField(blank=True, max_length=100)),
                ('special_effect', models.CharField(blank=True, max_length=100)),
                ('design', models.CharField(blank=True, max_length=100)),
                ('edit', models.CharField(blank=True, max_length=100)),
                ('audio_director', models.CharField(blank=True, max_length=100)),
                ('audio', models.CharField(blank=True, max_length=100)),
                ('sound_effect', models.CharField(blank=True, max_length=100)),
                ('movemaking', models.CharField(blank=True, max_length=100)),
                ('production', models.CharField(blank=True, max_length=100)),
                ('production_support', models.CharField(blank=True, max_length=100)),
                ('animate_production', models.CharField(blank=True, max_length=100)),
                ('sec_director', models.CharField(blank=True, max_length=100)),
                ('another_name', models.CharField(blank=True, max_length=100)),
                ('releast_time', models.CharField(blank=True, max_length=100)),
                ('official_web', models.CharField(blank=True, max_length=500)),
                ('broadcast_tv', models.CharField(blank=True, max_length=100)),
                ('scriptwriter', models.CharField(blank=True, max_length=100)),
                ('layout', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
