# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0002_infobox_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobox',
            name='acfun_bc',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='infobox',
            name='bilibili_bc',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='infobox',
            name='iqiyi_bc',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='infobox',
            name='letv_bc',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='infobox',
            name='tencent_bc',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='infobox',
            name='youku_bc',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
