# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-01 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0003_auto_20180131_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_jp', models.CharField(max_length=100)),
                ('name_cn', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('blood', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('homeplace', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=3000)),
            ],
        ),
    ]
