# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0007_auto_20180204_0707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
