# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0008_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_jp', models.CharField(blank=True, default='', max_length=100)),
                ('name_cn', models.CharField(blank=True, default='', max_length=100)),
                ('profession', models.CharField(blank=True, default='', max_length=50)),
                ('sex', models.CharField(blank=True, default='', max_length=10)),
                ('blood', models.CharField(blank=True, default='', max_length=10)),
                ('birthday', models.CharField(blank=True, default='', max_length=50)),
                ('height', models.CharField(blank=True, default='', max_length=10)),
                ('homeplace', models.CharField(blank=True, default='', max_length=100)),
                ('office', models.CharField(blank=True, default='', max_length=100)),
                ('hp', models.CharField(blank=True, default='', max_length=100)),
                ('twitter', models.CharField(blank=True, default='', max_length=50)),
                ('pixiv', models.CharField(blank=True, default='', max_length=50)),
                ('information', models.CharField(blank=True, default='', max_length=3000)),
            ],
        ),
    ]
