# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0009_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_jp', models.CharField(blank=True, default='', max_length=100)),
                ('name_cn', models.CharField(blank=True, default='', max_length=100)),
                ('sex', models.CharField(blank=True, default='', max_length=10)),
                ('birthday', models.CharField(blank=True, default='', max_length=50)),
                ('height', models.CharField(blank=True, default='', max_length=10)),
                ('weight', models.CharField(blank=True, default='', max_length=10)),
                ('constellation', models.CharField(blank=True, default='', max_length=50)),
                ('bwh', models.CharField(blank=True, default='', max_length=20)),
                ('information', models.CharField(blank=True, default='', max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='information',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
