# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0011_bangumi_character_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(blank=True, default='', max_length=200)),
                ('news_content', models.TextField(blank=True, default='')),
            ],
        ),
    ]
