# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0012_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bangumi_staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ani_id', models.IntegerField(blank=True, default=0)),
                ('person_id', models.IntegerField(blank=True, default=0)),
                ('person_name_jp', models.CharField(blank=True, default='', max_length=100)),
                ('person_name_cn', models.CharField(blank=True, default='', max_length=100)),
                ('profession', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
